### ISSUE TITLE
Is this abandoned?  I like the approach and am considering adopting it

### ISSUE THREAD

**Issue by zeroasterisk** [mattikl/redux-list-reducer#1]
I like this idea, and I think it should exists... reduce boilerplate on redux reducers, etc.

Have you been using it?

Have you considered using a tool like: https://github.com/kolodny/immutability-helper

**Comment by mattikl** [comment]
Thanks for your interest in this project. I'm not currently using it, but if you end up hacking on it, I'm interested in exploring the idea more.

I received basically no feedback after I released this over a year ago. I think the problem with this approach is that it makes many assumptions about the underlying data and introduces some limitations (for example, what if you need to save the data to a backend when it changes). And you need to understand exactly how it works to be able to trust it.

`immutability-helper` is a drop-in replacement for the former `react-addons-update`. I used it back in the day but switched to [ES6 spreads](http://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html) when they came around. [plainReducer.js](https://github.com/mattikl/redux-list-reducer/blob/master/src/plainReducer.js) uses ES6 spreads heavily.

**Comment by zeroasterisk** [comment]
Excellent - thanks for the review and the perspective on `immutability-helper`
